<a href="https://colab.research.google.com/github/Untick/Usedesk/blob/Vishnyakov-Dmitry-branch/%D0%A1%D1%82%D0%B0%D0%B6%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np # массивы
import pandas as pd # таблицы
from tensorflow.keras.models import Sequential # последовательная модель НС
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization # основные слои
from tensorflow.keras.layers import Activation # слой задания активационной функции
from tensorflow.keras import utils # утилиты предобработки данных
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split # разделение на обучающую и проверочную\тестовую выборки
import matplotlib.pyplot as plt # рисование графиков
%matplotlib inline

'sonar.csv'

In [15]:
df1 = pd.read_excel("Копия Витрина_Юздеск_2.xlsx")
df1.head()

,#NAME?,comp_id_new,месяц_desc,дата,рейтинг,всего,есть ответ,выполнен,закрыт,nps,...,u-task,u_problem,u_incident,u_low,u_medium,u_urgent,u_extreme,licens,бз,бз_ст
0,#NAME?,1,1,2023-06-01,2,3709,3442,578,2466,1231,...,0,0,0,0,2,0,0,13,1,4
1,#NAME?,1,2,2023-05-01,2,5573,5301,36,4715,2004,...,0,0,0,0,5,0,0,13,1,4
2,#NAME?,1,3,2023-04-01,2,6138,5983,4,5496,2242,...,0,0,0,0,1,0,0,13,1,4
3,#NAME?,1,4,2023-03-01,2,7834,7664,1,7094,2851,...,0,0,0,0,6,0,0,13,1,4
4,#NAME?,1,5,2023-02-01,2,7344,7252,1,6657,2686,...,0,0,0,0,2,0,0,13,1,4